# Generated by Django 5.2.8 on 2025-11-11 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hero', '勇者'), ('monster', 'モンスター')], max_length=20)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('skill', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image_hd2d', models.ImageField(blank=True, null=True, upload_to='characters/hd2d/')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_characters', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='database.game')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('effect', models.TextField(blank=True)),
                ('image_hd2d', models.ImageField(blank=True, null=True, upload_to='items/hd2d/')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='database.game')),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='dungeons/hd2d/')),
                ('hints', models.TextField(blank=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_dungeons', to=settings.AUTH_USER_MODEL)),
                ('monsters', models.ManyToManyField(blank=True, to='database.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeons', to='database.game')),
                ('reward_items', models.ManyToManyField(blank=True, to='database.item')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='database.game')),
            ],
        ),
    ]
