# Generated by Django 5.2.8 on 2025-11-25 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_range', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('strategy', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='levelguids/')),
            ],
        ),
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MAP概要', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('danger_level', models.CharField(choices=[('☆☆☆', '☆☆☆'), ('★☆☆', '★☆☆'), ('★★☆', '★★☆'), ('★★★', '★★★')], default='☆☆☆', max_length=3, verbose_name='危険度')),
                ('hp', models.IntegerField()),
                ('required_strength', models.CharField(blank=True, max_length=50, null=True, verbose_name='必要筋力')),
                ('strategy', models.TextField(blank=True, null=True, verbose_name='対処方法')),
                ('image', models.ImageField(blank=True, null=True, upload_to='monsters/')),
            ],
        ),
        migrations.CreateModel(
            name='OrbDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20)),
                ('damage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('melee', '近接武器'), ('ranged', '遠距離武器'), ('throw', '投擲武器'), ('trap', '設置武器'), ('treasure', '貴重品')], max_length=20)),
                ('rating', models.CharField(choices=[('☆☆☆', '☆☆☆'), ('★☆☆', '★☆☆'), ('★★☆', '★★☆'), ('★★★', '★★★')], max_length=3)),
                ('effect', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('upgrade', 'アップグレードパック'), ('heal', '回復パック'), ('drone', 'ドローン'), ('other', 'その他')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='攻撃名')),
                ('damage', models.CharField(blank=True, max_length=50, null=True, verbose_name='ダメージ')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='database.monster')),
            ],
        ),
    ]
